<div block-name="page-alert"></div>
<section class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="box  box-solid box-primary">
                <div class="box-header">
                    <i class="fa fa-cog"></i>
                    <h3 class="box-title"><?php echo $this->translate("Storages Options"); ?></h3>
                </div>
                <div class="box-body clearfix">
                    <div helper="form" action="<?php echo $this->url('admin/storages/options', ['action' => 'ajax']); ?>">
                        <div class="col-md-12">
                            <?php echo $this->form($form); ?>
                        </div>
                        <div class="control-group block">
                            <div class="controls">
                                <button type="submit" btn-name="send-form" class="btn btn-success pull-right"><i class="menu-icon icon-chevron-down"></i> Save Options</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>