<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/core.css');  ?>

    <!-- Scripts -->
    <script src="http://code.jquery.com/jquery.min.js"></script>
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/core.js'); ?>

</head>
<body>


<?php echo $this->content; ?>

<?php echo $this->inlineScript() ?>
</body>
</html>
