<?php
// Generated by ZF2's ./bin/templatemap_generator.php

return [
    'layout/layout'             => __DIR__ . '/layout/layout.phtml',

    'core/index'                => __DIR__ . '/index.phtml',

    'core/error/404'            => __DIR__ . '/error/404.phtml',
    'core/error/index'          => __DIR__ . '/error/index.phtml',

    'helper/core/pagination'          => __DIR__ . '/helper/pagination.phtml',
];
