<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>
    <title>Admin</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/admin.css'); ?>
    <?php echo $this->headScript(); ?>
    <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600' rel='stylesheet'>
</head>
<body>
<?php echo $this->content; ?>
<?php echo $this->inlineScript()->appendFile($this->basePath() . '/js/admin.js'); ?>
</body>
</html>
