<div block-name="page-alert"></div>

<section class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="box box-solid box-primary" block-name="form-module-options">
                <div class="box-header">
                    <i class="fa fa-cog"></i>
                    <h3 class="box-title"><?php echo $this->translate("User options"); ?></h3>
                </div>
                <div class="box-body clearfix">
                    <div helper="form" action="<?php echo $this->url('admin/users/options', ['action' => 'ajax']); ?>">
                        <form action="" method="POST" class="form-horizontal" role="form">


                            <div class="col-lg-3">
                                <div class="form-group "><label class="control-label">Default avatar</label>
                                    <div class="pr17">
                                        <button class="img-thumbnail" btn-name="admin-user-default-avatar" action="<?php echo $this->url('admin/users/options', ['action' => 'upload-avatar']); ?>">
                                            <input type="hidden" name="default_avatar_id" value="<?php echo $defaultAvatar ? $defaultAvatar->getId() : ''; ?>">
                                            <img <?php if(!$defaultAvatar) {?>style="display: none;"<?php }?> src="<?php echo $defaultAvatar ? $defaultAvatar->getMiddleFile()->getHref() : ''; ?>">
                                            <i class="fa fa-plus"></i>
                                            <input type="file" name="file">
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-9">
                                <div class="form-group ">
                                    <label class="control-label">Default role</label>
                                    <div class="">
                                        <?php echo $this->formElement($form->get('default_role_id')); ?>
                                    </div>
                                </div>

                                    <div class="form-group ">
                                        <label class="control-label">Default storage</label>
                                        <div class="">
                                            <?php echo $this->formElement($form->get('default_storage_id')); ?>
                                        </div>
                                    </div>

                            </div>
                        </form>
                        <div class="control-group block">
                            <div class="controls">
                                <button type="submit" btn-name="send-form" class="btn btn-success pull-right"><i
                                        class="menu-icon icon-chevron-down"></i> Save Options
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-6">
            <div class="box box-success" block-name="roles-manager" helper="table" action="<?php echo $this->url('admin/users/options'); ?>">
                <div class="box-header">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title"><?php echo $this->translate("Manage roles"); ?></h3>

                    <div class="box-tools" block-name="table-filters">
                        <div class="input-group pull-right">
                            <button btn-name="table-create-new" type="button" class="btn btn-success btn-sm ml10i">
                                <i class="fa fa-plus"></i>
                                <?php echo $this->translate("Add new role"); ?>
                            </button>
                        </div>
                    </div>
                </div>
                <hr>
                <?php $this->template_paginator = null; ?>
                <?php echo $this->adminBlockTable($this->variables); ?>
            </div>
        </div>
    </div>
</section>