<div block-name="page-alert"></div>

<section class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="box box-solid box-primary" block-name="form-module-options">
                <div class="box-header">
                    <i class="fa fa-cog"></i>
                    <h3 class="box-title"><?php echo $this->translate("Seo options"); ?></h3>
                </div>
                <div class="box-body clearfix">
                    <div helper="form" action="<?php echo $this->url('admin/seo/options', ['action' => 'ajax']); ?>">
                        <form action="" method="POST" class="form-horizontal" role="form">

                            <div class="col-lg-3">
                                <div class="form-group "><label class="control-label">Share image</label>
                                    <div class="pr17">
                                        <button class="img-thumbnail" btn-name="admin-load-share-image" action="<?php echo $this->url('admin/seo/options', ['action' => 'upload-image']); ?>">
                                            <input type="hidden" name="share_image_file_id" value="<?php echo $shareImage ? $shareImage->getId() : ''; ?>">
                                            <img <?php if(!$shareImage) {?>style="display: none;"<?php }?> src="<?php echo $shareImage ? $shareImage->getHref() : ''; ?>">
                                            <i class="fa fa-plus"></i>
                                            <input type="file" name="file">
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-9">
                                <div class="form-group ">
                                    <label class="control-label">Site title</label>
                                    <div class="">
                                        <?php echo $this->formElement($form->get('title')); ?>
                                    </div>
                                </div>
                                <div class="form-group "><label class="control-label">Title separator</label>
                                    <div class="">
                                        <?php echo $this->formElement($form->get('title_separator')); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="form-group "><label class="control-label">Site description</label>
                                    <div class="">
                                        <?php echo $this->formElement($form->get('description')); ?>
                                    </div>
                                </div>
                                <div class="form-group "><label class="control-label">Site keywords</label>
                                    <div class="">
                                        <?php echo $this->formElement($form->get('keywords')); ?>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="control-group block">
                            <div class="controls">
                                <button type="submit" btn-name="send-form" class="btn btn-success pull-right"><i
                                        class="menu-icon icon-chevron-down"></i> Save Options
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-4">
            <div class="box box-solid box-primary" block-name="form-module-options">
                <div class="box-header">
                    <i class="fa fa-cog"></i>
                    <h3 class="box-title"><?php echo $this->translate("Piwik acount"); ?></h3>
                </div>
                <div class="box-body clearfix">
                    <div helper="form" action="<?php echo $this->url('admin/seo/options', ['action' => 'piwik']); ?>">
                        <form action="" method="POST" class="form-horizontal" role="form">
                            <div class="col-lg-12">
                                <div class="form-group ">
                                    <label class="control-label"><?php echo $piwikForm->get('piwik_server_url')->getLabel(); ?></label>
                                    <div class="">
                                        <?php echo $this->formElement($piwikForm->get('piwik_server_url')); ?>
                                    </div>
                                </div>
                                <div class="form-group "><label class="control-label"><?php echo $piwikForm->get('piwik_access_token')->getLabel(); ?></label>
                                    <div class="">
                                        <?php echo $this->formElement($piwikForm->get('piwik_access_token')); ?>
                                    </div>
                                </div>
                                <div class="form-group "><label class="control-label"><?php echo $piwikForm->get('piwik_site_id')->getLabel(); ?></label>
                                    <div class="">
                                        <?php echo $this->formElement($piwikForm->get('piwik_site_id')); ?>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="control-group block">
                            <div class="controls">
                                <button type="submit" btn-name="send-form" class="btn btn-success pull-right"><i
                                        class="menu-icon icon-chevron-down"></i> Save Options
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>