
<div class="dataTables_info" id="DataTables_Table_0_info">Showing <?php echo $start; ?> to <?php echo $end; ?> of <?php echo $countAll; ?> entries</div>
<div block-name="options">

</div>
<div class="dataTables_paginate paging_two_button btn-group datatable-pagination">
    <a class="paginate_enabled_next">
        <span>Previous</span><i class="icon-chevron-left shaded"></i>
    </a>
    <a class="paginate_enabled_next">
        <span>Next</span><i class="icon-chevron-right shaded"></i>
    </a>
</div>
<div class="clearfix"></div>