<?php
// Generated by ZF2's ./bin/templatemap_generator.php
$path = __DIR__;
return array(
    'helper/storage/load_image'                 => __DIR__ . '/helper/load_image.phtml',




    'helper/storage/load/list_image'            => __DIR__ . '/view/helper/load_list_image.phtml',
    'helper/storage/load/list_image/block'      => __DIR__ . '/view/helper/load_list_image_block.phtml',
    'helper/storage/load_image_crop'            => __DIR__ . '/helper/load_image_crop.phtml',
);
